### ISSUE TITLE
Component Library Proposal: Buttons

### ISSUE THREAD

**Issue by melissaroman** [Ticketfly/ticketfly-ui#155]
@Ticketfly/frontenders 

As @spencer516 mentioned, he, Brian, and I met to chat about TFUI. This issue outlines a proposal for structuring the components that can be composed together to implement the features from the "Buttons" section of the design file.

(This proposal also assumes the existence of a tf-icon component.)

Feedback, questions, thoughts, and concerns all welcome!

**Button Categories**

TEMPLATE:

```hbs
{{#tf-button solid=true color-group='positive'}}Solid green button{{/tf-button}}
{{tf-button solid=true color-group='neutral' text="Solid indigo button"}}
{{tf-button solid=true color-group='negative' text="Solid red button"}}
{{#tf-button solid=false color-group='positive'}}Outlined green button{{/tf-button}}
{{tf-button solid=false color-group='neutral' text="Outlined indigo button"}}
{{tf-button solid=false color-group='negative' text="Outlined red button'}}
```

RESULTING HTML:

```html
<button class="c-button u-primary u-positive">Solid green button</button>
<button class="c-button u-primary u-neutral">Solid indigo button</button>
<button class="c-button u-primary u-negative">Solid red button</button>
<button class="c-button u-secondary u-positive">Outlined green button</button>
<button class="c-button u-secondary u-neutral">Outlined indigo button</button>
<button class="c-button u-secondary u-negative">Outlined red button</button>
```

**Button States**

TEMPLATE:

```hbs
{{tf-button solid=true color-group='positive' text="Active button"}} {{!-- active state is default --}}
{{#tf-button solid=true color-group='positive' disabled=true}}Disabled button{{/tf-button}}
```

RESULTING HTML:

```html
<button class="c-button u-primary u-positive">Active button</button> 
<button class="c-button u-primary u-positive" disabled="disabled">Disabled button</button>
```

**Buttons with Icons**

TEMPLATE:

```hbs
{{tf-icon-button as |i|}}
  {{i.icon "plus"}}
  {{i.text text="Add a thing"}}
{{/tf-icon-button}}
```

RESULTING HTML:

```html
<button class="c-button u-primary u-neutral">
  <span class="c-tf-icon tf-plus"></span>
  <span>Add a thing</span>
</button>
```

**Comment by melissaroman** [comment]
@BrianSipple @spencer516 
- Since this component is just using CSS classes, why not make put it in the CSS utils file?
- Components slow down the app by about 15-30ms per component.
- Often we want buttons to be <a> tags under the hood – it is more semantically correct. The component mandates <button>. The button utility classes should be usable on both <button> and <a>
- Use same language as design. Keep primary and secondary names.
- Avoid binary configuration options (true / false).
- Beware of utility class naming conflicts `.u-positive` (`.u-button-positive` instead)


#### API Ideas:
```
.button__primary--positive
.tf-button .u-button-primary .u-button-positive
```

```
// Selects all elements with class that begins with “button__”
// http://www.w3schools.com/css/css_attribute_selectors.asp
[class*=“button__”] {
  border: none;
  display: inline-block;
}

[class*=“button__”]:disabled {
  // disabled styles
}

[class*=“button__primary”] {
  background: indigo;
}

[class*=“button__secondary”] {
  border: 1px solid indigo;
  background: transparent;
}

[class*=“button__primary--negative”] {
  background-color: red;
}
```
### Icons
```
- Put icons IN button
- Icon classes should have icon in naming (tf-icon-circle-plus)
```

#### API Ideas:
```
[class*=“button__”]:before {
  // Icon specific styling
}
[class*=“button__”] i[class*=“tf-"]{
  // Icon specific styling
}
```

**Comment by spencer516** [comment]
Melissa and I discussed this a bit in person, but thought I would transcribe some of the thoughts here. 

> Since this component is just using CSS classes, why not make put it in the CSS utils file?

I think longer term, there are some advantages of going the component route as it'll make it easier for developers to consume buttons and such. It also means that we have more flexibility in the future to make some changes without breaking everyone's apps. 

> Components slow down the app by about 15-30ms per component.

There is certainly a risk of introducing performance issues with using _too many_ components and is worth considering. That being said, Glimmer 2, which will likely land before we've begun using this, reduces the per-component cost dramatically and we may not need to worry about it. I'd rather we prioritize ease-of-use over performance, then get "closer to the metal" on a case-by-case basis.

**Comment by ksin** [comment]
Has there been discussion on what an action button looks like when it's in-flight? (ie: loading state after clicking a Save button). The Sketch file I have have only seems to cover Static, Hover, and Disabled states. Similarly, there doesn't seem to be a spec for Error state.

If we are going with button components, how much state should the buttons hold versus the consumer managing the state (and just rendering another button when the state changes)?

For example, using the button state to yield different text on the button:
```
{{#tf-button action=(action "save") as |btn|}}
  {{#if (equals btn.state 'saving')}}
    Loading...
  {{/if}}
  {{#if (equals btn.state 'failed')}}
    Error!
  {{/if}}
  {{#if (equals btn.state 'saved')}}
    Saved!
  {{/if}}
{{/tf-button}}
```
alternatively, in the component template:
```
{{#if (equals state 'saving')}}
  Loading...
{{else}}
  {{yield}}
{{/if}}
```
and the js would look something like:
```
click(evt) {
    evt.preventDefault();
    let promise = this.attrs.action();
    if (!promise || !promise.then) {
      return;
    }

    set(this, 'state', 'saving');
    promise.then(() => {
      set(this, 'state', 'saved');
    }, () => {
      set(this, 'state', 'failed');
    })
  }
```

Again, we can say No to all that and just have the parent manage state and render a new button every time the state changes. Just some things to consider with an action button component.

**Comment by spencer516** [comment]
@ksin — I think I bought that question up at one point. In the short term, since it's not specified in the designs, we can probably punt on this for now (But, I think it's worthwhile to make sure we're designing an API that would easily allow for this type of functionality in the future).

**Comment by ksin** [comment]
Initial implementation based on the specs above https://github.com/Ticketfly-UI/ticketfly-button
Perhaps move the discussion to issues in that repository

**Comment by ksin** [comment]
Barebones implementation based on the specs above https://github.com/Ticketfly-UI/ticketfly-buttons
Perhaps move the discussion to issues in that repository

**Comment by spencer516** [comment]
I'm going to close as we've adopted this proposal.
