### ISSUE TITLE
Use `ember-ticketfly-ui-css` in Dummy App / Isolate this repo as a demo

### ISSUE THREAD

**Issue by BrianSipple** [Ticketfly/ticketfly-ui#156]
Related to #154, #147, and #152.

The ultimate architecture for Ticketfly UI should look as follows (I'll update with something spiffier if I get the chance 😄): 

![img_20161120_140555](https://cloud.githubusercontent.com/assets/5483853/20474121/d8b04c50-af79-11e6-9ece-eecffff94a41.jpg)

That would leave this repo as space to integrate both `ember-ticketfly-ui-css` and our individual Ticketfly UI Ember Components in order to build out a full-fledged showcase for our design specifications.

**Comment by melissaroman** [comment]
@BrianSipple Can you explain this in person just so I can make sure I understand it as you intend it?

**Comment by melissaroman** [comment]
@BrianSipple and @spencer516 

A few questions regarding the above structure. I actually talked in depth with my friend at linkedin who has made their entire pattern library and is now revising it based on some initial issues they ran into so I think we could benefit from that knowledge. Not that we need to do it exactly like them but some ideas...

- CSS - put the foundational stuff in CSS repo (grid, colors, fonts, etc.) and then the component CSS within each component ember addon (separation of concerns, lessens dependencies)

- Since we are an ember shop, we don’t really need the separate CSS and ‘ember-ticketfly-ui’ -> merge these two into ‘ember-ticketfly-foundations’

- Is there a reason we AREN'T using SASS? I know you can do all the same things with a CSS Post Processor but it seems much less out-of-the-box.

- Instead of just delivering CSS classes, deliver mixins and functional vars so that there are no peer dependencies at all. Example below:

```
// End Consumer / Developer

  // application.hbs
  <h1 class="ticketfly-text-24px ticketfly-text-bold">Header!</h1>
  {{#ticketfly-button}}{{/ticketfly-button}}

  // app.css
  @import "ticketfly-foundations";
  @import "ticketfly-button";
  
  // can do custom-selectors if we have mixins
  custom-selector {
    @include ticketfly-text-24px();
    border-top: 5px solid get-color(indigo);
  }

===================================

// Ember Ticketfly Foundations

  // Option 1 (purely class-based):
  .ticketfly-text-24px { font-size: 24px; }
  .ticketfly-text-bold { font-weight: bold; }

  // Option 2:
  // We can import either a) index.css which delivers classes, or b) just core.css that *only* delivers    mixins – no classes are output.

  // core.css
  @mixin ticketfly-text-24px() { font-size: 24px; }
  @mixin ticketfly-text-bold() { font-weight: bold; }
  @function get-color($name) { ... return hex value; }

  // index.css
  @import core.css;
  .ticketfly-text-24px { @include ticketfly-text-24px(); }
  .ticketfly-text-bold { @include ticketfly-text-bold(); }


===================================

// Ember Ticketfly Button (component)

  // Option 1 (foundations are always a peer dep. - not good):

  // addon.hbs
  <h1 class="ticketfly-text-24px ticketfly-text-bold">Header!</h1>
  {{#ticketfly-button}}{{/ticketfly-button}}

  // addon.css
  @import "ticketfly-foundations";

  // Option 2, build standalone (good!):
  // Only import core, no classes delivered. Built by postcss before being published (postcss happens in component).
  // Completely standalone CSS in the end.

  // addon.hbs
  <h1 class="ticketfly-button">Header!</h1>
  {{#ticketfly-button}}{{/ticketfly-button}}

  // addon.css
  @import "ticketfly-foundations/core";

  ticketfly-button {
    @include ticketfly-text-24px();
  }

  // addon.css (built)
  ticketfly-button {
    font-size: 24px;
  }
```

**Comment by BrianSipple** [comment]
@melissaroman 

Regarding some of those ideas....

> CSS - put the foundational stuff in CSS repo (grid, colors, fonts, etc.) and then the component CSS within each component ember addon (separation of concerns, lessens dependencies)

👍 That's the goal of [ticketfly-css](https://github.com/Ticketfly-UI/ticketfly-css)

> Since we are an ember shop, we don’t really need the separate CSS and ‘ember-ticketfly-ui’ -> merge these two into ‘ember-ticketfly-foundations’

This seems like an unnecessary coupling of concerns. _We're_ an Ember shop, sure, but the goal first and foremost is to have something that can be used anywhere, by anyone. 

> Is there a reason we AREN'T using SASS? I know you can do all the same things with a CSS Post Processor but it seems much less out-of-the-box.

I wish I organized some of my thoughts better -- a lot of this information is available in the guild presentation I gave in October. In short, though, the benefits are massive. PostCSS is affords both pre- and post-processing functionalities, meaning we can do everything we could do with pre-processing language like SASS, and a lot more that would be fundamentally impossible with a pre-processor (think [runtime context](https://philipwalton.com/articles/why-im-excited-about-native-css-variables/)).

**Comment by melissaroman** [comment]
@BrianSipple 

Having both the CSS repo AND the ember-ticketfly repo still seems like extra dependencies to me. Maybe something more to chat about. 

And cool on the other two topics! 👍 

Any thoughts on delivering mixins versus just classes?

**Comment by BrianSipple** [comment]
@melissaroman I don't think dependencies would be a huge concern. For a user, it's transparent -- if your using Ember, you use `ember-ticketfly-css`. If not, you use `ticketfly-css`. 

The separation allows us to version, build, and test `ticketfly-css` without being tied to anything in Ember, and vice versa.

Also, regarding mixins, I generally find them unnecessary at a framework level -- but that's something we'll figure out as we go 😄 .

**Comment by BrianSipple** [comment]
I know I mentioned it in our Slack discussion, but I just wanted to formalize a few more thoughts here...

My main stance is that merging the two repos is a recipe for a lot of pain -- both for developers and users. It offers little benefit because having two repos managing things is, itself, a huge win here.

We cripple ourselves if we try to develop an addon with the mentality of "users shouldn't have to know it's an Ember addon". This places an necessary but _massive_ constraint on our feature set, our development architecture, and our testing architecture.

At the same time, we cripple users because... they kind of do. An ember-addon, in it's most basic form, depends on `ember-cli` and `ember-cli-babel`. And so if there's any sort of dependency benefit with one approach or the other, it would be with the one that doesn't require consumers to install a litany of packages that they don't want to use.

Furthermore, to elaborate on testing, the testing story vastly different between Ember and Node. Ember’s testing architecture is meant to test Ember factories registered by the application’s resolver during initialization. It’s not suited for actively accessing the file system in node. A pure Node-based library, however, can do exactly that. (See the [current test suite of `ticketfly-css`](https://github.com/Ticketfly-UI/ticketfly-css/blob/master/test/index.spec.js) for an example).

**Comment by BrianSipple** [comment]
@spencer516  @melissaroman An additional point. I believe there’s a fundamental incompatibility with an ember addon and a CSS library. 

When building an addon, ember-cli will always [search for the project’s main entry point](https://ember-cli.com/extending/#addon-entry-point) and attempt to run any blueprints. 

With an npm package that distributes CSS, we’ll want to denote the entry point (via the “main” property of `package.json`) as the main css distribution file. This will allow other CSS modules to declare an `@import` statement with the package name (for example, `@import “ticketfly-css-alignment”). [See this issue for a bit more context](https://github.com/postcss/postcss-import/issues/101). Again, though, it seems like we’d be introducing a huge and rather unnecessary risk of things flat out not working with a coupled architecture.

**Comment by spencer516** [comment]
A few thoughts:

- We would not need the `ember-cli-babel` dependency as this is a non-javascript package. 
- All other dependencies, including `ember-cli` are in `devDependencies`, so those would not be installed when a user installs the package. 
- The issue you referenced discussed the multiple ways that a CSS project is resolved — the "main" entry point is one; `index.css` and the "style" attribute in `package.json` are others. The latter two options do not conflict with making this an Ember-CLI project. 
- Making this an Ember addon does not mean we would need to change the testing story. For example, most of the Deploy Plugins (which are ember addons) run their tests with Mocha ([example](https://github.com/ember-cli-deploy/ember-cli-deploy-s3/blob/master/tests/runner.js)) — similar to how you've set up the tests

This is the part I'm still not quite understanding:

> At the same time, we cripple users because... they kind of do

Can you elaborate on how this would cripple users? Which users? 

The issues that Melissa highlighted left me a little bit worried about this approach — _especially_ if we're deliberately not taking advantage of some of the ways Ember-CLI can help us here. I think the case for making this separate is valid, but they might make more sense when this is a mature project. 

In the short term, I think this is going to make it harder for us to develop this project.

**Comment by melissaroman** [comment]
I went over the structure of the LinkedIn styleguide last night and this is how they have it set up. Adam is still happy to come in and go over what they learned, what went wrong the first time around, what they're changing (to have it more like what is below). But just to see the structure, here are some sketches.

CSS-Core (They use scss but that doesn't really matter.):
![css](https://cloud.githubusercontent.com/assets/7133272/21237610/8a09afa8-c2b4-11e6-8ee0-54d74fe3adfa.JPG)

Ember Component Example:
![component](https://cloud.githubusercontent.com/assets/7133272/21237615/90ddbbc6-c2b4-11e6-84c4-e365c3fc1e9f.JPG)

Consuming App:
![consuming-app](https://cloud.githubusercontent.com/assets/7133272/21237644/b21b97c2-c2b4-11e6-8b46-e300d291f1c0.JPG)

**Comment by BrianSipple** [comment]
@melissaroman This is useful -- thanks! 

We all seem to be on the same page regarding the overarching path: raw CSS --> ember-addon wrapping it --> ember-component.

I still maintain my points about the benefit of keeping each piece as their own projects, though. Did Adam have any opinions about why they combined their CSS with an Ember addon?

**Comment by melissaroman** [comment]
@BrianSipple 

There are only TWO things up there other than the consuming app. The Ember part of the CSS repo is a part of that, not a separate repo. This is my main point actually with the dependencies issue.

This way either Ember devs or non-Ember devs can easily use this (although given we're an Ember shop, that should be our main focus.

**Comment by melissaroman** [comment]
Oops, I didn't see your second question in the email. Sorry, @BrianSipple!

Yeah, his strong stance was to limit the dependencies and dev management with the extra repo when there is no benefit in his eyes to having an 'ember-wrapper' in addition to the CSS repo. The ember files can be easily added into the CSS repo without harming the CSS usability for anyone who isn't using Ember. But at the same time, this is being built primarily for Ticketfly and can be installed as an Ember addon with those files. He actually knows the structure of our company and team so isn't blindly suggesting we combine those two files.

Another note I'd like to make here is that my Ember Conf talk is focusing on limiting the dependencies so I'm going to be discussing these points and would like to be able to use Ticketfly as an example. I don't really want to say that 'this is the best way to limit dependencies...' but we do it differently at TF.

**Comment by BrianSipple** [comment]
@melissaroman Hey, I'm totally on board with limiting unnecessary dependencies. That said, I'm not sure I understand how the number of dependencies -- or which dependencies -- would change with either approach.

**Comment by spencer516** [comment]
As I understand it — dependencies with Brian's approach:

1. `ticketfly-css`
2. `ember-ticketfly-css`

Dependencies with Melissa's approach:

1. `ticketfly-css` (which includes necessary Ember-CLI code)

The _other_ dependencies that include the components and such would not change between these two options. (Though, there's an open question there: should those include their CSS and Javascript? I think that's another potential disagreement we haven't directly addressed).

**Comment by melissaroman** [comment]
@BrianSipple I'd like to merge the CSS and 'ember-wrapper' repos down to one. So, managing one fewer repos (and therefore one less place for dependencies to be an issue).

**Comment by BrianSipple** [comment]
I guess it depends on how we define `dependency`, haha. 

My definition of a dependency is "What bytes are we shipping to the user when they use this". Regardless of whether or not we have separate repos for `ticketfly-css` and `ember-ticketfly-css`, the dependency to someone using either one would be the CSS distributed by the framework. 

(@spencer516 I asserted earlier that the addon would force `ember-cli-babel` on users, but I believe you're correct that we would be able to remove it from our `package.json`.)
